services:
  - type: web
    name: RAJASTHANI
    plan: free
    env: docker
    dockerfilePath: Dockerfile
    repo: https://github.com/vashu5uhsav-art/5
    branch: main
    autoDeploy: false
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: OWNER
        sync: false
      - key: CREDIT
        sync: false
      #- key: WEBHOOK
        #sync: false
      - key: PORT
        value: 10000  # Default port value, update if needed
